apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: tf-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tf-backend
      purpose: backend
  template:
    metadata:
      labels:
        app: tf-backend
        purpose: backend
    spec:
      containers:
      - name: backend
        image: sintaxiz/tf-backend
        volumeMounts:
        - name: script-volume
          mountPath: "/app/temp-scripts"
      - name: manager
        image: sintaxiz/tf-manager
      volumes:
      - name: script-volume
        persistentVolumeClaim:
          claimName: backend-pvc
