# Node Port: ClusterIP + open ports on nodes and all requests on this ports will redirect to service
apiVersion: v1
kind: Service
metadata:
  name: np-tf-frontend
spec:
  type: NodePort # by default ClusterIP
  selector:
    app: tf-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31234